# Generated by Django 5.2.17 on 2026-08-13 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'تلگرام'), ('whatsapp', 'واتس\u200cاپ')], max_length=16, unique=True, verbose_name='پیام\u200cرسان')),
                ('is_enabled', models.BooleanField(default=False, verbose_name='فعال')),
                ('token', models.CharField(blank=True, help_text='تلگرام: توکنی که BotFather می\u200cدهد. واتس\u200cاپ: توکن دسترسی سرویس\u200cدهنده.', max_length=255, verbose_name='توکن ربات')),
                ('phone_number_id', models.CharField(blank=True, help_text='فقط واتس\u200cاپ — شناسه شماره\u200cای که پیام از آن ارسال می\u200cشود.', max_length=64, verbose_name='شناسه شماره فرستنده')),
                ('api_base', models.CharField(blank=True, help_text='خالی بگذارید تا آدرس پیش\u200cفرض استفاده شود.', max_length=255, verbose_name='آدرس پایه سرویس')),
                ('webhook_secret', models.CharField(blank=True, help_text='برای تأیید اینکه پیام واقعاً از سرویس\u200cدهنده آمده است.', max_length=128, verbose_name='کلید امنیتی وب\u200cهوک')),
                ('last_update_id', models.BigIntegerField(default=0, verbose_name='آخرین شناسه دریافت')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
            ],
            options={
                'verbose_name': 'تنظیمات ربات',
                'verbose_name_plural': 'تنظیمات ربات\u200cها',
            },
        ),
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('telegram', 'تلگرام'), ('whatsapp', 'واتس\u200cاپ')], db_index=True, max_length=16, verbose_name='پیام\u200cرسان')),
                ('direction', models.CharField(choices=[('in', 'دریافتی'), ('out', 'ارسالی')], db_index=True, max_length=4, verbose_name='جهت')),
                ('status', models.CharField(choices=[('ok', 'موفق'), ('unknown', 'فرستنده ناشناس'), ('unparsed', 'دستور نامفهوم'), ('failed', 'خطا')], db_index=True, default='ok', max_length=12, verbose_name='وضعیت')),
                ('sender_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='شناسه فرستنده')),
                ('text', models.TextField(blank=True, verbose_name='متن پیام')),
                ('error', models.CharField(blank=True, max_length=255, verbose_name='خطا')),
                ('external_id', models.CharField(blank=True, db_index=True, max_length=128, verbose_name='شناسه پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
                ('party', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bot_messages', to='core.party', verbose_name='طرف حساب')),
            ],
            options={
                'verbose_name': 'پیام ربات',
                'verbose_name_plural': 'پیام\u200cهای ربات',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['platform', '-created_at'], name='bots_botmes_platfor_a1bd0a_idx'), models.Index(fields=['sender_id', '-created_at'], name='bots_botmes_sender__0c41a8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('direction', 'in'), models.Q(('external_id', ''), _negated=True)), fields=('platform', 'external_id'), name='uniq_incoming_bot_message')],
            },
        ),
    ]
