# Generated by Django 5.2.17 on 2026-08-12 07:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RateSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان')),
                ('kind', models.CharField(choices=[('manual', 'ورود دستی'), ('http_json', 'سرویس اینترنتی (JSON)')], default='manual', max_length=16, verbose_name='نوع')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='آدرس سرویس')),
                ('api_key', models.CharField(blank=True, help_text='در صورت نیاز، در آدرس با {api_key} جایگزین می\u200cشود.', max_length=255, verbose_name='کلید API')),
                ('timeout_seconds', models.PositiveSmallIntegerField(default=10, verbose_name='مهلت پاسخ (ثانیه)')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
            ],
            options={
                'verbose_name': 'منبع نرخ',
                'verbose_name_plural': 'منابع نرخ',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=8, unique=True, verbose_name='کد')),
                ('name', models.CharField(max_length=32, verbose_name='نام')),
                ('symbol', models.CharField(blank=True, max_length=8, verbose_name='نماد')),
                ('decimal_places', models.PositiveSmallIntegerField(default=2, verbose_name='تعداد اعشار')),
                ('is_base', models.BooleanField(default=False, help_text='ارزی که همه چیز نسبت به آن سنجیده می\u200cشود. فقط یک ارز می\u200cتواند پایه باشد.', verbose_name='ارز پایه')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
            ],
            options={
                'verbose_name': 'ارز',
                'verbose_name_plural': 'ارزها',
                'ordering': ['sort_order', 'code'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_base', True)), fields=('is_base',), name='only_one_base_currency')],
            },
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('customer', 'مشتری'), ('bank', 'بانک'), ('cashbox', 'صندوق'), ('position', 'موقعیت ارزی صرافی'), ('expense', 'هزینه'), ('equity', 'سرمایه')], db_index=True, default='customer', max_length=16, verbose_name='نوع')),
                ('name', models.CharField(max_length=128, verbose_name='نام')),
                ('code', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='کد حساب')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='شماره تماس')),
                ('national_id', models.CharField(blank=True, max_length=32, verbose_name='کد ملی / شناسه')),
                ('telegram_id', models.CharField(blank=True, db_index=True, max_length=64, verbose_name='شناسه تلگرام')),
                ('whatsapp_no', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='شماره واتس\u200cاپ')),
                ('is_system', models.BooleanField(default=False, help_text='حساب\u200cهای سیستمی قابل حذف نیستند.', verbose_name='حساب سیستمی')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='فعال')),
                ('note', models.TextField(blank=True, verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('currency', models.ForeignKey(blank=True, help_text='برای بانک، صندوق و موقعیت ارزی الزامی است. مشتری\u200cها چندارزی\u200cاند و خالی می\u200cماند.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parties', to='core.currency', verbose_name='ارز حساب')),
            ],
            options={
                'verbose_name': 'طرف حساب',
                'verbose_name_plural': 'طرف حساب\u200cها',
                'ordering': ['kind', 'name'],
                'indexes': [models.Index(fields=['kind', 'is_active'], name='core_party_kind_07df64_idx')],
            },
        ),
        migrations.CreateModel(
            name='FxRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_to_base', models.DecimalField(decimal_places=8, max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='نرخ به ارز پایه')),
                ('source_label', models.CharField(blank=True, max_length=64, verbose_name='عنوان منبع')),
                ('effective_at', models.DateTimeField(db_index=True, verbose_name='زمان اعتبار')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rates', to='core.currency', verbose_name='ارز')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rates', to='core.ratesource', verbose_name='منبع')),
            ],
            options={
                'verbose_name': 'نرخ ارز',
                'verbose_name_plural': 'نرخ\u200cهای ارز',
                'ordering': ['-effective_at', '-id'],
                'indexes': [models.Index(fields=['currency', '-effective_at'], name='core_fxrate_currenc_10143d_idx')],
            },
        ),
        migrations.CreateModel(
            name='RateSourceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('json_path', models.CharField(help_text='مسیر نقطه\u200cای تا عدد نرخ. مثال: "aed.value" یا "data.0.price"', max_length=255, verbose_name='مسیر مقدار در پاسخ')),
                ('multiplier', models.DecimalField(decimal_places=8, default=Decimal('1'), help_text='اگر سرویس نرخ را به تومان می\u200cدهد و پایه شما ریال است، ۱۰ بگذارید.', max_digits=18, verbose_name='ضریب تبدیل')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_mappings', to='core.currency', verbose_name='ارز')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='core.ratesource', verbose_name='منبع')),
            ],
            options={
                'verbose_name': 'نگاشت نرخ',
                'verbose_name_plural': 'نگاشت\u200cهای نرخ',
                'constraints': [models.UniqueConstraint(fields=('source', 'currency'), name='uniq_source_currency_mapping')],
            },
        ),
    ]
