# Generated by Django 5.2.17 on 2026-08-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='kind',
            field=models.CharField(choices=[('customer', 'مشتری'), ('bank', 'بانک'), ('cashbox', 'صندوق'), ('position', 'موقعیت ارزی صرافی'), ('expense', 'دسته\u200cبندی هزینه'), ('income', 'دسته\u200cبندی درآمد'), ('equity', 'سرمایه')], db_index=True, default='customer', max_length=16, verbose_name='نوع'),
        ),
    ]
