# Generated by Django 5.2.17 on 2026-08-12 07:56

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=32, unique=True, verbose_name='کلید')),
                ('value', models.BigIntegerField(default=0, verbose_name='مقدار فعلی')),
            ],
            options={
                'verbose_name': 'شمارنده',
                'verbose_name_plural': 'شمارنده\u200cها',
            },
        ),
        migrations.CreateModel(
            name='InventoryPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28, verbose_name='موجودی')),
                ('avg_unit_cost', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28, verbose_name='میانگین بهای هر واحد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='آخرین تغییر')),
                ('currency', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='position', to='core.currency', verbose_name='ارز')),
            ],
            options={
                'verbose_name': 'موقعیت ارزی',
                'verbose_name_plural': 'موقعیت\u200cهای ارزی',
            },
        ),
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='شماره سند')),
                ('kind', models.CharField(choices=[('deal', 'معامله (خرید/فروش ارز)'), ('receive', 'دریافت'), ('pay', 'پرداخت'), ('transfer', 'انتقال داخلی'), ('adjust', 'اصلاحی'), ('opening', 'افتتاحیه')], db_index=True, max_length=16, verbose_name='نوع سند')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('final', 'قطعی'), ('void', 'باطل')], db_index=True, default='draft', max_length=8, verbose_name='وضعیت')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('description', models.TextField(blank=True, verbose_name='شرح')),
                ('external_key', models.CharField(blank=True, help_text='ضد ثبت تکراری. اگر همین کلید قبلاً ثبت شده باشد، سند دوباره ثبت نمی\u200cشود.', max_length=128, null=True, unique=True, verbose_name='کلید یکتا')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان ثبت')),
                ('finalized_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان قطعی شدن')),
                ('void_reason', models.CharField(blank=True, max_length=255, verbose_name='علت ابطال')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vouchers_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('reverses', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversed_by', to='ledger.voucher', verbose_name='سند برگشتیِ')),
            ],
            options={
                'verbose_name': 'سند',
                'verbose_name_plural': 'اسناد',
                'ordering': ['-date', '-number', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_no', models.PositiveSmallIntegerField(default=1, verbose_name='ردیف')),
                ('amount', models.DecimalField(decimal_places=8, max_digits=28, verbose_name='مبلغ (+بدهکار / −بستانکار)')),
                ('rate_to_base', models.DecimalField(decimal_places=8, default=Decimal('1'), help_text='نرخ ارز در لحظه ثبت. بعداً تغییر نمی\u200cکند.', max_digits=28, verbose_name='نرخ قفل\u200cشده')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='شرح سطر')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.currency', verbose_name='ارز')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.party', verbose_name='طرف حساب')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='ledger.voucher', verbose_name='سند')),
            ],
            options={
                'verbose_name': 'سطر سند',
                'verbose_name_plural': 'سطرهای سند',
                'ordering': ['voucher_id', 'row_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('side', models.CharField(choices=[('buy', 'خرید'), ('sell', 'فروش')], db_index=True, max_length=4, verbose_name='نوع معامله')),
                ('quantity', models.DecimalField(decimal_places=8, max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='تعداد ارز')),
                ('unit_price', models.DecimalField(decimal_places=8, max_digits=28, validators=[django.core.validators.MinValueValidator(Decimal('1E-8'))], verbose_name='نرخ هر واحد')),
                ('total_base', models.DecimalField(decimal_places=8, max_digits=28, verbose_name='مبلغ کل')),
                ('avg_cost_at_time', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28, verbose_name='میانگین بهای تمام\u200cشده در لحظه معامله')),
                ('realized_pnl', models.DecimalField(decimal_places=8, default=Decimal('0'), max_digits=28, verbose_name='سود/زیان تحقق\u200cیافته')),
                ('date', models.DateField(db_index=True, verbose_name='تاریخ')),
                ('counterparty', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='core.party', verbose_name='طرف معامله')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='deals', to='core.currency', verbose_name='ارز')),
                ('voucher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deal', to='ledger.voucher', verbose_name='سند')),
            ],
            options={
                'verbose_name': 'معامله',
                'verbose_name_plural': 'معاملات',
                'ordering': ['-date', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['-date', '-id'], name='ledger_vouc_date_1729ea_idx'),
        ),
        migrations.AddIndex(
            model_name='voucher',
            index=models.Index(fields=['kind', 'status'], name='ledger_vouc_kind_edec26_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['party', 'currency', 'date'], name='ledger_entr_party_i_c28bec_idx'),
        ),
        migrations.AddIndex(
            model_name='entry',
            index=models.Index(fields=['currency', 'date'], name='ledger_entr_currenc_c2ea3a_idx'),
        ),
        migrations.AddConstraint(
            model_name='entry',
            constraint=models.CheckConstraint(condition=models.Q(('amount', 0), _negated=True), name='entry_amount_not_zero'),
        ),
        migrations.AddIndex(
            model_name='deal',
            index=models.Index(fields=['currency', 'side', 'date'], name='ledger_deal_currenc_e40071_idx'),
        ),
    ]
