# Generated by Django 5.2.17 on 2026-08-17 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ledger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='kind',
            field=models.CharField(choices=[('deal', 'معامله (خرید/فروش ارز)'), ('receive', 'دریافت'), ('pay', 'پرداخت'), ('transfer', 'انتقال داخلی'), ('adjust', 'اصلاحی'), ('opening', 'افتتاحیه'), ('expense', 'هزینه'), ('income', 'درآمد')], db_index=True, max_length=16, verbose_name='نوع سند'),
        ),
    ]
