# Generated by Django 5.2.17 on 2026-08-12 07:56

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=64, unique=True, verbose_name='کد')),
                ('title', models.CharField(max_length=128, verbose_name='عنوان')),
                ('group_title', models.CharField(blank=True, max_length=64, verbose_name='دسته')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
            ],
            options={
                'verbose_name': 'مجوز',
                'verbose_name_plural': 'مجوزها',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(max_length=32, unique=True, verbose_name='کد')),
                ('title', models.CharField(max_length=64, verbose_name='عنوان نقش')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='توضیح')),
                ('is_system', models.BooleanField(default=False, verbose_name='نقش سیستمی')),
                ('permissions', models.ManyToManyField(blank=True, related_name='roles', to='accounts.permission', verbose_name='مجوزها')),
            ],
            options={
                'verbose_name': 'نقش',
                'verbose_name_plural': 'نقش\u200cها',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('full_name', models.CharField(blank=True, max_length=128, verbose_name='نام و نام خانوادگی')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='شماره تماس')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='users', to='accounts.role', verbose_name='نقش')),
            ],
            options={
                'verbose_name': 'کاربر',
                'verbose_name_plural': 'کاربران',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username_snapshot', models.CharField(blank=True, max_length=150, verbose_name='نام کاربری')),
                ('action', models.CharField(choices=[('login', 'ورود به سیستم'), ('login_failed', 'ورود ناموفق'), ('logout', 'خروج از سیستم'), ('create', 'ایجاد'), ('update', 'ویرایش'), ('delete', 'حذف'), ('post', 'قطعی کردن سند'), ('void', 'ابطال سند'), ('export', 'خروجی گرفتن'), ('rate_fetch', 'دریافت نرخ ارز')], max_length=24, verbose_name='عملیات')),
                ('model_name', models.CharField(blank=True, max_length=64, verbose_name='جدول')),
                ('object_id', models.CharField(blank=True, max_length=64, verbose_name='شناسه رکورد')),
                ('summary', models.CharField(blank=True, max_length=255, verbose_name='شرح')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='آی\u200cپی')),
                ('user_agent', models.CharField(blank=True, max_length=255, verbose_name='مرورگر')),
                ('before', models.JSONField(blank=True, null=True, verbose_name='مقدار قبل')),
                ('after', models.JSONField(blank=True, null=True, verbose_name='مقدار بعد')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='زمان')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'تاریخچه تغییر',
                'verbose_name_plural': 'تاریخچه تغییرات',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['model_name', 'object_id'], name='accounts_au_model_n_76c60d_idx'), models.Index(fields=['action', '-created_at'], name='accounts_au_action_f18cdc_idx')],
            },
        ),
    ]
