# Generated by Django 5.2.17 on 2026-08-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='برای کاربرانی که با رمز پیش\u200cفرض ساخته شده\u200cاند تا رمز را عوض نکرده\u200cاند.', verbose_name='باید رمز را عوض کند'),
        ),
    ]
